// Welcome to DAX query view! Learn more about DAX queries at https://aka.ms/dax-queries.
// Right-click on tables, columns, or measures in the data pane to access quick queries, or ask Copilot for help writing DAX.

// Select "Run" to try this sample DAX query.
EVALUATE
VAR __TabTop1Anos =
ADDCOLUMNS(
    ALLSELECTED(dim_calendario[Ano]),
    "@Top1Cat",
    CONCATENATEX(
        TOPN(
            1,
            ALLSELECTED(dim_product_categories[product_category_name]),
            [$ Exportacoes], DESC
        ),
        dim_product_categories[product_category_name]
    )
)

RETURN
__TabTop1Anos